title: Python notebooks
author: Pierre Navaro
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

execute:
  execute_notebooks: force

html:
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://pnavaro.github.io/python-notebooks

repository:
  url: https://github.com/pnavaro/python-notebooks
  branch: master
  path_to_book: notebooks

launch_buttons:
  notebook_interface: "classic" 
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true

execute:
  timeout: 300
